name: Build application 

on:
  push:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build-and-test-frontend:
    name: Build frontend project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Install UI
        run: |
          cd ui
          ./install_ui

  build-and-test-backend:
    name: Build backend project
    runs-on: ubuntu-latest
    needs: build-and-test-frontend

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.1'
          distribution: 'zulu'

      - name: Cache build artifacts
        uses: actions/cache@v2.1.5
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-bar-${{ github.sha }}

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Test with Maven
        run: mvn test

  create-docker-image:
    name: "Create docker image"
    needs: build-and-test-backend

    runs-on: ubuntu-latest

    if: success()

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.5
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-bar-${{ github.sha }}

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v3.2.1
        with:
          dockerfile: docker/Dockerfile
          image-name: bom-bar
          tags: 0 0.2 0.2.0 v0.2.0 latest
