name: Get licenses

on:
  push:

jobs:
  scanLicenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.13' 
        distribution: 'zulu'

    - name: Create spdx-file
      id: spdx-builder
      uses: philips-software/spdx-action@v0.9.1.1
      with:
        project: bom-bar
        ort-version: latest
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: licenses
        path: ${{ steps.spdx-builder.outputs.spdx-file }}
