name: Get licenses

on:
  push:

jobs:
  scanLicenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.13'
        distribution: 'zulu'

    - name: Create dependencies list
      run: |
        ./mvnw dependency:tree 
        ./mvnw dependency:tree > dependencies.txt

    - name: Show dependencies.txt
      run: |
        cat dependencies.txt

    - name: Create spdx-file
      id: spdx-builder
      uses: philips-software/spdx-action@v0.9.2
      with:
        project: bom-bar
        mode: 'tree'
        tree: dependencies.txt
        format: maven

    - uses: actions/upload-artifact@v3
      with:
        name: licenses
        path: ${{ steps.spdx-builder.outputs.spdx-file }}
